### ISSUE TITLE
Can't change clippy contents

### ISSUE THREAD

**Issue by zwhitchcox** [jimmysawczuk/clippy-jquery#16]
If I set clippy with $('.clippy').clippy({text:'hello'})

and then later on invoke $('.clippy').clippy({text:'wello'})

the text that is on the clipboard is still "hello".

I also tried $('#single_clippy').clippy({text: "This is a test"});, but it did not change the text on my clipboard at all.

**Comment by jimmysawczuk** [comment]
Are you actually recopying? This plugin can't change the contents of your clipboard without you clicking the clippy button. (I'd imagine that's the same for most similar plugins.)

However, I was able to change the text by copying once, then running `$.clippy`, then copying again, as intended.

**Comment by zwhitchcox** [comment]
Sorry, I actually meant to close this, but yes, that's what I was doing wrong.
